// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servanda.Infrastructure.Data;

#nullable disable

namespace Servanda.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ServandaDbContext))]
    [Migration("20260814072419_AddToolsAndPromptsSchema")]
    partial class AddToolsAndPromptsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Servanda.Domain.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccentKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("accent_key");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_hidden");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey")
                        .IsUnique()
                        .HasFilter("availability = 'active' AND archived_at IS NULL");

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.HasIndex("ArchivedAt", "IsHidden", "SortOrder");

                    b.ToTable("areas", null, t =>
                        {
                            t.HasCheckConstraint("ck_areas_availability", "availability IN ('active', 'planned')");

                            t.HasCheckConstraint("ck_areas_revision", "revision > 0");

                            t.HasCheckConstraint("ck_areas_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Catalog.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "SortOrder")
                        .IsUnique()
                        .HasFilter("parent_id IS NULL");

                    b.HasIndex("ParentId", "AreaId");

                    b.HasIndex("AreaId", "ParentId", "SortOrder")
                        .IsUnique()
                        .HasFilter("parent_id IS NOT NULL");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_parent", "parent_id IS NULL OR parent_id <> id");

                            t.HasCheckConstraint("ck_categories_revision", "revision > 0");

                            t.HasCheckConstraint("ck_categories_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Catalog.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("ck_tags_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.Prompt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_favorite");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("CategoryId", "AreaId");

                    b.HasIndex("CategoryId", "SortOrder")
                        .IsUnique();

                    b.ToTable("prompts", null, t =>
                        {
                            t.HasCheckConstraint("ck_prompts_revision", "revision > 0");

                            t.HasCheckConstraint("ck_prompts_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptTag", b =>
                {
                    b.Property<string>("PromptId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<string>("TagId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_id");

                    b.HasKey("PromptId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("prompt_tags", (string)null);
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptUsageEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("PromptId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<string>("PromptTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_title");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("used_at");

                    b.Property<string>("VariantId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("variant_name");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.HasIndex("UsedAt");

                    b.HasIndex("VariantId");

                    b.ToTable("prompt_usage", (string)null);
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVariable", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<bool>("IsMultiline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_multiline");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "Name")
                        .IsUnique();

                    b.HasIndex("PromptId", "SortOrder")
                        .IsUnique();

                    b.ToTable("prompt_variables", null, t =>
                        {
                            t.HasCheckConstraint("ck_prompt_variables_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVariant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Target")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "SortOrder")
                        .IsUnique();

                    b.ToTable("prompt_variants", null, t =>
                        {
                            t.HasCheckConstraint("ck_prompt_variants_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt_id");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_json");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "CreatedAt");

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("Servanda.Domain.Tools.Tool", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("area_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "AreaId");

                    b.HasIndex("CategoryId", "GroupKey", "SortOrder")
                        .IsUnique();

                    b.ToTable("tools", null, t =>
                        {
                            t.HasCheckConstraint("ck_tools_group_key", "group_key IN ('featured', 'regular')");

                            t.HasCheckConstraint("ck_tools_revision", "revision > 0");

                            t.HasCheckConstraint("ck_tools_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Tools.ToolTag", b =>
                {
                    b.Property<string>("ToolId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("tool_id");

                    b.Property<string>("TagId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("tag_id");

                    b.HasKey("ToolId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("tool_tags", (string)null);
                });

            modelBuilder.Entity("Servanda.Infrastructure.Data.AppState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentEpoch")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_epoch");

                    b.HasKey("Id");

                    b.ToTable("app_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Servanda.Infrastructure.Data.OrderingScope", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_key");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ScopeKey");

                    b.ToTable("ordering_scopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_ordering_scopes_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Servanda.Domain.Catalog.Category", b =>
                {
                    b.HasOne("Servanda.Domain.Areas.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servanda.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId", "AreaId")
                        .HasPrincipalKey("Id", "AreaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Servanda.Domain.Catalog.Tag", b =>
                {
                    b.HasOne("Servanda.Domain.Areas.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.Prompt", b =>
                {
                    b.HasOne("Servanda.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "AreaId")
                        .HasPrincipalKey("Id", "AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptTag", b =>
                {
                    b.HasOne("Servanda.Domain.Prompts.Prompt", null)
                        .WithMany("Tags")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servanda.Domain.Catalog.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptUsageEntry", b =>
                {
                    b.HasOne("Servanda.Domain.Prompts.Prompt", null)
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Servanda.Domain.Prompts.PromptVariant", null)
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVariable", b =>
                {
                    b.HasOne("Servanda.Domain.Prompts.Prompt", null)
                        .WithMany("Variables")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVariant", b =>
                {
                    b.HasOne("Servanda.Domain.Prompts.Prompt", null)
                        .WithMany("Variants")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.PromptVersion", b =>
                {
                    b.HasOne("Servanda.Domain.Prompts.Prompt", null)
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Tools.Tool", b =>
                {
                    b.HasOne("Servanda.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId", "AreaId")
                        .HasPrincipalKey("Id", "AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Tools.ToolTag", b =>
                {
                    b.HasOne("Servanda.Domain.Catalog.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servanda.Domain.Tools.Tool", null)
                        .WithMany("Tags")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servanda.Domain.Prompts.Prompt", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Variables");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Servanda.Domain.Tools.Tool", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
