// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servanda.Infrastructure.Data;

#nullable disable

namespace Servanda.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ServandaDbContext))]
    partial class ServandaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Servanda.Domain.Areas.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccentKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("accent_key");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_hidden");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("module_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey")
                        .IsUnique()
                        .HasFilter("availability = 'active' AND archived_at IS NULL");

                    b.HasIndex("SortOrder")
                        .IsUnique();

                    b.ToTable("areas", null, t =>
                        {
                            t.HasCheckConstraint("ck_areas_availability", "availability IN ('active', 'planned')");

                            t.HasCheckConstraint("ck_areas_revision", "revision > 0");

                            t.HasCheckConstraint("ck_areas_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Servanda.Infrastructure.Data.AppState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentEpoch")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_epoch");

                    b.HasKey("Id");

                    b.ToTable("app_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("Servanda.Infrastructure.Data.OrderingScope", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_key");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ScopeKey");

                    b.ToTable("ordering_scopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_ordering_scopes_revision", "revision > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
