<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servanda.Infrastructure\Servanda.Infrastructure.csproj" />
  </ItemGroup>

</Project>
